# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('pickup_address', models.CharField(max_length=2000)),
                ('pincode', models.IntegerField()),
                ('phone_brand', models.CharField(max_length=200)),
                ('phone_model', models.CharField(max_length=200)),
                ('phone_fault', models.CharField(max_length=200)),
                ('alternate_contact_number', models.IntegerField()),
                ('optional_message', models.CharField(max_length=2000)),
                ('date_of_request', models.DateTimeField(verbose_name='Date of servece request')),
            ],
        ),
    ]
