# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_text',
            field=models.CharField(default='req1', max_length=200),
            preserve_default=False,
        ),
    ]
